### ISSUE TITLE
no prompts please

### ISSUE THREAD

**Issue by pelikhan** [platformio/platformio#196]
Please remove all blocking prompts from the command line. It breaks automation scenario easily.

I know there are various settings to disable but prompts are just a bad idea for a command line tool environment. If i wanted prompts, i'd be using an IDE.

**Comment by ivankravets** [comment]
How about this issue https://github.com/platformio/platformio/issues/152 ?

Do you recommend to disable prompts by default?

**Comment by pelikhan** [comment]
It should be the default. Prompts  might not occur during development time but happen later on the production server due to an update.

**Comment by ivankravets** [comment]
I'm not sure that we should link "prompts" with "IDE". We have a lot of console utilities where prompts are used, like ``rm`` with ``--force`` option. Prompts are good for PlatformIO because the allow:

1. Initialise new project with a few questions as for correct project directory, use/or not use automatic uploading and etc.
2. Allow to paginate via search result form ``platformio lib search`` command. Because I can't show ALL result by user request.
3. It allow to avoid problem with internet connection when PlatformIO detect that platform is not installed and ask user to install it. In this case a few hundred megabytes will be used for downloading depending packages.

--------
I implemented ``--force`` option for ALL platformio command which will allow to avoid blocking. See https://github.com/platformio/platformio/issues/152

Like, ``platformio --force COMMAND OPTIONS``

**Comment by pelikhan** [comment]
Ok will add force. I find prompts in all command lines utterly annoying, I guess that's just me :)

Sent from Outlook<http://taps.io/outlookmobile>




On Thu, May 14, 2015 at 2:26 PM -0700, "Ivan Kravets" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure that we should link "prompts" with "IDE". We have a lot of console utilities where prompts are used, like rm with --force option. Prompts are good for PlatformIO because the allow:

  1.  Initialise new project with a few questions as for correct project directory, use/or not use automatic uploading and etc.
  2.  Allow to paginate via search result form platformio lib search command. Because I can't show ALL result by user request.
  3.  It allow to avoid problem with internet connection when PlatformIO detect that platform is not installed and ask user to install it. In this case a few hundred megabytes will be used for downloading depending packages.

________________________________

I implemented --force option for ALL platformio command which will allow to avoid blocking. See #152<https://github.com/platformio/platformio/issues/152>

Like, platformio --force COMMAND OPTIONS

-

**Comment by ivankravets** [comment]
> I guess that's just me

I hope you will like PlatformIO 2.0 :smile: Thanks a lot for your ideas and interest.
