### ISSUE TITLE
Add libOpenCM3 framework for nucleo_f103rb board

### ISSUE THREAD

**Issue by eliabieri** [platformio/platformio#309]
At the moment, the nucleo_f103rb board only supports mbed.

**Comment by ivankravets** [comment]
@valeros has uploaded updated [libOpenCM3](http://docs.platformio.org/en/latest/frameworks/libopencm3.html) framework. Please update it via `platformio update` command

This issue is fixed in PlatformIO 2.4.0.dev0. Try development build http://docs.platformio.org/en/latest/installation.html#development-version
