### ISSUE TITLE
Make it possible to install libraries by name 

### ISSUE THREAD

**Issue by FWeinb** [platformio/platformio#414]
It would be much easier to just install a library by name instead of a cryptic id number. And having names in the `platformio.ini` would also improve readability.

**Comment by ivankravets** [comment]
I don't remember where I've written an answer for this question. The problem here is that PlatformIO Library Registry can contain more than one library with the same name. For example, it can have different `WiFi` libraries per platforms.

As solution, nee to allow to install library by name but when more than libs are found, then ask user which lib to install. Or use like `WiFi#13`, where is 100% link to lib by ID. 

Also, you have requested #410 . In this case it might look like `WiFi#13@~0.13.2`. The format will be discussed.

**Comment by FWeinb** [comment]
Can it be guaranteed that the combination of platform + libraryname is unique? If that is the case, the package manager could derive the platform from the `platformio.ini` and try to search for the specific package. How is this currently handled, can a project using board=uno and board=esp01 depend on a library that only support the uno?

**Comment by ivankravets** [comment]
> Can it be guaranteed that the combination of platform + libraryname is unique?

This is not PlatformIO guaranty. The owner of the lib specifies which frameworks and platforms are supported. Currently, there are no any checks for compatibility. PlatformIO builds all that user asks. See #415

**Comment by jasonmhite** [comment]
> The problem here is that PlatformIO Library Registry can contain more than one library with the same name. For example, it can have different WiFi libraries per platforms.

Wouldn't it make sense to ask for a particular selection if there are multiple options that match a given name? Something like "there are multiple libraries that match the name <foolib>, choes one of: 1. foo1 2. foo2 3. foo3"? Similarly, when building with `platformio run`, if it runs into a conflict then it can pause and ask for the proper choice and simply remember that in the future, perhaps by writing to `platformio.ini`.

**Comment by ivankravets** [comment]
@jasonmhite this is `feature` issue, I'll implement it.
