### ISSUE TITLE
Add support for AVR XMEGA

### ISSUE THREAD

**Issue by knutel** [platformio/platformio#481]
It would be great to have support for AVR XMEGA, too. There already is a project to make Arduino support at [https://github.com/Xmegaduino/Xmegaduino], so maybe PlatformIO support is not that difficult. I might take a stab at it myself if I get the time.

**Comment by aethaniel** [comment]
Hi @knutel, I took a look at Xmegaduino repo and also did some google search around boards based on Xmega.
Unfortunately, it seems the Xmegaduino would need some love to turn into a dedicated Arduino 1.6.x module and also some available boards.
Furthermore, this arduino port doesn't seem to be maintained since years and is still in beta. 

I didn't seen any strong request for Xmega support in Arduino forum either but it can be explained by all small ARM Cortex-M0(+) devices fighting on the market segment.

Besides that, AVR GCC and all needed tools are available for out-of-framework tinkering.

**Comment by knutel** [comment]
Agreed, maybe the effort required is better spent elsewhere. Feel free to close this one.

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platform-atmelavr/issues/21
