### ISSUE TITLE
Support Mbed OS (3.x) with yotta build

### ISSUE THREAD

**Issue by georgeedwards** [platformio/platformio#640]
As you may be aware, the mbed team are in the final stages of rolling out the yotta build engine to support the new Mbed OS system of building applications for their hardware. 

As far as I know, this isn't supported in platformo currently (I would love to be corrected on this). If that is the case, are there any plans to support it, if not - can we make some?

**Comment by ivankravets** [comment]
Sorry for the off-top. I see request https://raw.githubusercontent.com/Gas-Sense/ble/master/library.json

Does this lib work with PlatformIO?

**Comment by georgeedwards** [comment]
@ivankravets yes, I have tested it manually moving it into the project and it works well!

**Comment by ivankravets** [comment]
The `BLE_API` library has been added. http://platformio.org/lib/show/296/BLE_API

**Comment by georgeedwards** [comment]
@ivankravets Thanks! Any thougths on yotta?

**Comment by ivankravets** [comment]
PlatformIO uses own Build System that works everywhere without dependences. `yotta` depends on CMake and Ninja Build System. You will have ability in PlatformIO 3.0 to write own development platform and replace our Build System with `yotta`.

The best option here is to write native PlatformIO System Build script for Mbed OS. We will try to find sponsors for this feature because we don't have enough resources for 3-rd parties tools.

**Comment by ivankravets** [comment]
@valeros , please switch all development platforms to new builder for ARM mbed and close this issue.

**Comment by ivankravets** [comment]
PlatformIO 3.0 supports to build Mbed OS
