### ISSUE TITLE
Multi-file arduino project does not build

### ISSUE THREAD

**Issue by saschaludwig** [platformio/platformio#730]
Here is a multi-file project which has problems building in platformio ide 1.3.6 cli 2.11.1:
https://github.com/ESP8266nu/ESPEasy

I get quite a number of errors like this:
`/Users/sl/ownCloud/Arduino/ESPEasy/src/_P006_BMP085.ino:54:39: error: 'Plugin_006_bmp085_begin' was not declared
 in this scope`

Could it be there is a problem with underscores in the .ino filenames?
How could this be fixed?

Thanks, Sascha

**Comment by palfrey** [comment]
You need to declare functions in C before you use them, or in this particular case, re-order the functions so that you start with functions in a file that don't need any of your other ones, then the ones that only need the ones you've declared so far, and so on.

http://stackoverflow.com/questions/14307087/whats-wrong-with-this-arduino-code has a good example of the type of thing.

**Comment by ivankravets** [comment]
PlatformIO Build System has own INO to CPP auto converter. See
- https://github.com/platformio/platformio/blob/develop/platformio/builder/tools/piomisc.py#L26

It looks like it doesn't convert code very well. I'll look on it later.

**Comment by ivankravets** [comment]
Please re-test with PlatformIO 3.0 http://docs.platformio.org/en/stable/installation.html#development-version

**Comment by saschaludwig** [comment]
Tested with PlatformIO 3.0: code does compile now.
Thank you very much! Awesome work
